### ISSUE TITLE
Pressing enter delays action by 1 key & input speed loses focus

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [koca/vue-prism-editor#62] opened 2020-04-07 05:58 UTC
I got it working and noticed that when I press enter it doesn't put my cursor on the next line until I press another key. This really throws me off.

Also typing really fast seems to mess up the editor and lose input focus. I was deleting a row of text and it stopped deleting and it was because I had to click on the editor again to re-focus. I tried just typing like I would normally code and it did the same thing. It seems you cannot type fast at all?

I'm testing on Firefox for both of these issues. Is there a potential fix?

**Comment by wadewilliams** [comment] 2020-04-24 16:30
Duplicate of #65 I think -- Seeing the same problem

**Comment by koca** [comment] 2020-08-08 08:05
Released new version [v1](https://github.com/koca/vue-prism-editor/releases/tag/v1.0.1) 🎉

**Closed by koca** 2020-08-08 08:05 UTC
